### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by mashabow** [LettError/ufoProcessor#1]
Would you upload this package to PyPI? It makes easier to use ufoProcessor + fontTools.designspaceLib in place of designSpaceLib.

**Comment by LettError** [comment]
No objection, but I don't have experience with that. Also: I imagine there will be considerable changes to ufoProcessor still. I don't know if that is an issue.

**Comment by miguelsousa** [comment]
The package is now on PyPI https://pypi.org/project/ufoProcessor/
Next step is to automate the deployment of future versions.
