### ISSUE TITLE
what about using VariationModel instead of MutatorMath?

### ISSUE THREAD

**Issue by anthrotype** [LettError/ufoProcessor#2]
would it be possible/desirable?
And how difficult would it be?
Do we need to change the VariationModel API in fonttools, or we can wrap it here somehow so that we could apply it on fontMath objects?

**Comment by LettError** [comment]
Sorry for some reason I don't get all notifications. Maybe. Can VariationModel extrapolate already?

**Comment by LettError** [comment]
*  `getInfoMutator()`
*  `getKerningMutator()`
*  `getGlyphMutator()`
* ... should return objects with a `makeInstance(location)`

**Comment by LettError** [comment]
This https://github.com/LettError/ufoProcessor/blob/designspacelib-layer/Lib/ufoProcessor/__init__.py#L331 allows the choice between mutatormath and varlib.

**Comment by LettError** [comment]
Axismapping is now also done with varLib.model.
