### ISSUE TITLE
Question: <glyphs> vs. <rules>

### ISSUE THREAD

**Issue by madig** [LettError/ufoProcessor#23]
IIUC, the `<glyphs>` element in an instance can be used to synthesize new glyphs for instances or overwrite existing ones. How are the following comment to be understood? https://github.com/LettError/ufoProcessor/blob/21ae7b4e571387bff3aeb7ab0bbf17991023cb23/Lib/ufoProcessor/__init__.py#L696-L697
https://github.com/LettError/ufoProcessor/blob/21ae7b4e571387bff3aeb7ab0bbf17991023cb23/Lib/ufoProcessor/__init__.py#L740

Does it mean that the "replace" part should be done with `<rules>` instead? That the `<glyphs>` element should be deprecated? Something else?

**Comment by LettError** [comment]
FWIW, the glyphs element was an early method to record the outcome of rule-like actions. Now that there is a clear idea of how the rules work, it is not necessary to do this any more.

**Comment by madig** [comment]
Ok, thanks for the clarification :)
