### ISSUE TITLE
Use version numbers

### ISSUE THREAD

**Issue by colinmford** [LettError/ufoProcessor#27]
https://github.com/LettError/ufoProcessor/blob/062a1c272e0cfd1fb3157524ad8aa2575d5bb5ab/Lib/ufoProcessor/__init__.py#L32-L35

Currently the version number is unknown, so it is tough to keep track of what version of ufoProcessor is included in RoboFont, for instance.

Even if it is 0.0.1.dev0, it would be helpful to know.

**Comment by anthrotype** [comment]
that's probably because robofont does not include the autogenerated ufoProcessor._version module.

**Comment by anthrotype** [comment]
ufoProcessor uses setuptools_scm to generate the version string from the git tag, see https://github.com/LettError/ufoProcessor/blob/062a1c272e0cfd1fb3157524ad8aa2575d5bb5ab/setup.py#L16

RoboFont should not simply clone the repro and copy over the source files as is, but it should at least do a `python setup.py build` and copy the resulting files in the build/lib directory (including the generated _version.py module). Or it download/build a wheel, pip install to a temporary prefix and copy over the content of that.

**Comment by anthrotype** [comment]
we use this same approach basically everywhere (perhaps excluding fonttools where version string is hard-coded in __init__.py), so RoboFont should make sure to make this work reliably.

**Comment by colinmford** [comment]
My mistake, Thanks.

**Comment by colinmford** [comment]
cc @typemytype
