### ISSUE TITLE
Generated Instances missing Kerning

### ISSUE THREAD

**Issue by colinmford** [LettError/ufoProcessor#28]
Hi there,

[MM vs UP.zip](https://github.com/LettError/ufoProcessor/files/4276823/MM.vs.UP.zip)

I was noticing that with this test font, generating a designspace with ufoProcessor results in instances _without_ kerning, while generating from MutatorMath results in instances _with_ kerning.

MM code:
```python
from mutatorMath.ufo.document import DesignSpaceDocumentReader
myPath = "Romans Full.designspace"

doc = DesignSpaceDocumentReader(myPath, 3, roundGeometry=True, verbose=True)
doc.process(makeGlyphs=True, makeKerning=True, makeInfo=True)
```

UP code:
```python
import ufoProcessor

myPath = "Romans Full.designspace"
ufoProcessor.build(myPath, roundGeometry=True, useVarlib=False)
```

**Comment by colinmford** [comment]
Is there anything wrong with my ufoProcessor code that would result in my files missing kerning? Does anyone else have a similar issue or is anyone else able to reproduce my issue?

**Comment by LettError** [comment]
This happened because the sourceDescriptors assumed layer name is set to None for foreground layers. Fix is coming up.

**Comment by colinmford** [comment]
Thank you!
