### ISSUE TITLE
What is the best way to extract a MathGlyph, once generated?

### ISSUE THREAD

**Issue by arrowtype** [LettError/ufoProcessor#42]
First, I’m not sure if this is necessarily a ufoProcessor issue, but it’s related to me trying to use ufoProcessor. I’m struggling a bit, and not entirely sure where to ask for clarification. If you think I should file this elsewhere, please let me know!

I have a [quick-and-dirty script](https://gist.github.com/arrowtype/18fb1b009ad09d34f8c081792bf526e4) to help with the manual syncing of support sources within a larger designspace. In summary:
- I have full sources at weights 1, 700, and 1000
- I have partial, suppose sources at weights 100, 200, 500, and 800. These are used to control stroke contrast in stroke joints and shaping in dot shapes (dot accents, periods, commas, quotes, etc)
- My script helps me to sync the support sources with updates to the main sources, by:
  - Generating interpolated spacing , and updating that automatically in the supports
  - Generating interpolated glyph shapes, and placing those in the background layer of the supports, so I can adjust support shaping to them as desired

If it’s useful, I described this all in more detail during [a TypeLab talk which is currently available in this video, at 3h30m](https://www.youtube.com/watch?v=m_4c9IyLcM8&t=12634s).

My script has a few limitations: probably the worst thing is that it requires a user to select one designspace _with_ supports, and one without, and then it goes from there. It also probably doesn’t accept designspace v5, and it is relatively slow. It also relies on being run from within RoboFont, which is fine, but not ideal. It is also just kind of messy, and I’m trying to make it better, as a learning exercise.

So, I’d like to clean up that script and move it to the latest ufoProcessor. [Here’s a WIP version of the new script.](https://gist.github.com/arrowtype/47937ba868b0b2a49e80684319e56037).

My current blocker is that I can generate glyphs if I use a bunch of try/except blocks, to skip logic that fails. However, if I don’t use a try/except block on the part that syncs spacing, it fails to sync spacing on every glyph that has uses a component. 

As far as I can tell, this is because I am generating a `MathGlyph` object with ufoProcessor, and then extracting it into a defcon Glyph object. But, then this defcon glyph object crashes when it tries to report attributes like `leftMargin` and `width`, if it includes a component.

Here is roughly how I am creating the new glyph, which I want to copy info from to update my support source:

```python 
            # go through each glyph in manually edited support source
            for g1 in supportSourceFont:
                
                # make a mutator / varlib object for glyph name
                glyphMutator = openedGeneratorDS.getGlyphMutator(g1.name)

                # create glyph outlines for the current support location
                g2MathGlyph = glyphMutator.makeInstance(location)
                
                # round the glyph geometry
                g2MathGlyph =g2MathGlyph.round()

                # create a new generic glyph object
                g2 = defcon.Glyph()

                # extract the math glyph into the new glyph object
                g2MathGlyph.extractGlyph(g2)
```

But, as soon as my script gets to a glyph with a component, Defcon crashes.

```
<RGlyph 'questiondown' ('public.default') at 4590857008>
<defcon.objects.glyph.Glyph object at 0x111273760>
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/defcon/objects/component.py", line 183, in drawPoints
    pointPen.addComponent(self._baseGlyph, self._transformation, identifier=self.identifier)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/pens/pointPen.py", line 264, in addComponent
    self.pen.addComponent(glyphName, transform)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/pens/basePen.py", line 217, in addComponent
    glyph = self.glyphSet[glyphName]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/name-sans/source/01-name_sans-robofont_scripts/supports/update-sparse-source-spacing-including_italics-2.robofont.py", line 422, in <module>
    spacingDiffs = checkForSpacingDiffs(g1, g2)
  File "/Users/stephennixon/type-repos/name-sans/source/01-name_sans-robofont_scripts/supports/update-sparse-source-spacing-including_italics-2.robofont.py", line 270, in checkForSpacingDiffs
    generatedGlyphDimensions = (round(glyph2.width), round(glyph2.leftMargin), round(glyph2.rightMargin))
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/defcon/objects/glyph.py", line 286, in _get_leftMargin
    bounds = self.bounds
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/defcon/objects/glyph.py", line 267, in _get_bounds
    return self._getContourComponentBounds("bounds")
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/defcon/objects/glyph.py", line 258, in _getContourComponentBounds
    b = getattr(subObject, attr)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/defcon/objects/component.py", line 124, in _get_bounds
    return self.getRepresentation("defcon.component.bounds")
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/defcon/objects/base.py", line 342, in getRepresentation
    return factory["factory"](self, **kwargs)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/defcon/tools/representations.py", line 92, in componentBoundsRepresentationFactory
    obj.draw(pen)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/defcon/objects/component.py", line 176, in draw
    self.drawPoints(pointPen)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/defcon/objects/component.py", line 185, in drawPoints
    pointPen.addComponent(self._baseGlyph, self._transformation)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/pens/pointPen.py", line 264, in addComponent
    self.pen.addComponent(glyphName, transform)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/pens/basePen.py", line 217, in addComponent
    glyph = self.glyphSet[glyphName]
TypeError: 'NoneType' object is not subscriptable
```

My current guess is, it’s crashing because my script is only generating this current glyph, but not the parent glyph to support components. So, that leaves me with some questions...

1. Should I instead just generate the full instance, as I was previously doing, and copy spacing and shaping info from that? If so, how? This is what I’ll try next... I’ll update this issue if I can figure it out!
2. Is there a better way than Defcon to create a generic Glyph() object, to extract the MathGlyph into? I also tried creating a Glyph object with FontParts, using my support source’s background layer, but then FontParts wouldn’t allow me to extract anchors into it.

I’ve experimented quite a bit, but many aspects of this are somewhat fuzzy to me, so it’s hard to know whether I’m going about this in the right way... So, if I’m asking the wrong questions, I’m also happy to be redirected.

I’m happy to email sources directly, if that helps. 

Thank you for any pointers or insights!

**Comment by arrowtype** [comment]
Oh, nice. Turns out, taking time to write this issue was exactly what I needed to do to figure it out. 😅

Indeed, generating the full instance was what I needed. Here’s roughly how I am doing that:

```python
# a list of locations to check
supportLocations = {}

# first, we make a dict of sparse sources and their locations
for dsSource in openedMainDS.sources:
    if "sparse" in dsSource.filename or "support" in dsSource.filename:
        supportLocations[dsSource] = dsSource.location

# then we loop through the instances of the "generator" designspace
for dsInstance in generatorDS.instances:
    # and check if it matches a support source 
    for supportSource, location in supportLocations.items():
        if dsInstance.location == location:

            report[supportSource.path] = ""
            
            # # open support source as RFont ... should we use RF’s OpenFont() to access angledLeftMargin, etc?
            supportSourceFont = Font(supportSource.path, showInterface=False)
            print(supportSourceFont)

            # feed the instance object into makeInstance from ufoProcessor, to generate that font
            generatedInstance = openedGeneratorDS.makeInstance(dsInstance)

            # copy glyph outlines and info as needed
```

**Comment by LettError** [comment]
Have you looked at ufoOperator?

**Comment by arrowtype** [comment]
Oh, actually, one further update: I’ve realized it is helpful to wrap the `makeInstance()` line in FontParts’s `OpenFont()` function, in order to round the glyph geometry of the generated glyphs. (I can’t figure out if there is a more built-in way to do this, but I wasn’t finding it...)

```Python
# at the top of the script
from fontParts.world import OpenFont
```

```Python
            # feed the instance object into makeInstance from ufoProcessor, to generate that font
            # but wrap this in the FontParts OpenFont() to allow manipulation of the glyph (i.e. rounding coordinates)
            generatedInstance = OpenFont(openedGeneratorDS.makeInstance(dsInstance))
```

Anyway, I think I’ve answered my questions here, so I’ll close the issue. I’m still very happy to get any pointers or corrections on this... I recognize that I’m probably doing about 1000 things in a non-ideal way. 😄

**Comment by arrowtype** [comment]
> Have you looked at ufoOperator?

Oh... I sort of had, but then I hadn’t quite realized it was something to separately import. I somehow thought that, since the `ds5` branch was merged in, and the readme didn’t really say otherwise, that ufoOperator just _was_ what I was getting by importing ufoProcessor. But, looking again, it looks like ufoOperator is a Class within ufoProcessor?

I’ll keep poking around.

**Comment by arrowtype** [comment]
It sort of seems like I get all the functionality I need from importing `DesignSpaceProcessor`... but, should I be doing something to specifically use `ufoOperator`? Sorry if this is a silly question. I still don’t have a clear mental model of everything here, and how I should best use it.

**Comment by arrowtype** [comment]
Ah, I guess the script does fail as soon as I try to read a ds5 that includes separate roman and italic variable fonts. Is there some way to use ufoOperator to get past that?


```
▶ python source/01-name_sans-robofont_scripts/supports/update-sparse-source-spacing-including_italics-2.robofont.py 
<RFont 'AT Name Sans Text Thin' path='/Users/stephennixon/type-repos/name-sans/source/masters/sparse--Name_Sans-Text_100.ufo' at 4376017360>
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/name-sans/source/01-name_sans-robofont_scripts/supports/update-sparse-source-spacing-including_italics-2.robofont.py", line 342, in <module>
    generatedInstance = OpenFont(openedGeneratorDS.makeInstance(dsInstance))
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/ufoProcessor/__init__.py", line 674, in makeInstance
    kerningMutator = self.getKerningMutator()
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/ufoProcessor/__init__.py", line 422, in getKerningMutator
    bias, self._kerningMutator = self.getVariationModel(kerningItems, axes=self.serializedAxes, bias=kerningBias)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/ufoProcessor/__init__.py", line 323, in getSerializedAxes
    return [a.serialize() for a in self.axes]
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/ufoProcessor/__init__.py", line 323, in <listcomp>
    return [a.serialize() for a in self.axes]
AttributeError: 'DiscreteAxisDescriptor' object has no attribute 'serialize'
```

**Comment by LettError** [comment]
ok, another quick shot, addressing the first question, have you looked at fontparts' fromMathGlyph ?

https://github.com/robotools/fontParts/blob/f5250dc93916f45d5bf3e286cf44ff4c7dad9965/Lib/fontParts/base/glyph.py#L1668C18-L1668C18

**Comment by LettError** [comment]
UFOOperator is a rewrite of UFOProcessor, to support DS5. It offers the same services and should be easy to switch to.

**Comment by arrowtype** [comment]
I didn’t know about `fromMathGlyph()`... I’ll give it a try!

And awesome, that’s good to hear that the difference is pretty simple. I’ll give it another try. 

Thanks so much for your help here!

**Comment by arrowtype** [comment]
Sure enough, ufoOperator was quite seamless to move to!

```python
# import it
from ufoProcessor.ufoOperator import UFOOperator

# open main DS & fonts with ufoProcessor.ufoOperator
mainDS = DesignSpaceDocument.fromfile(mainDSpath)
openedMainDS = UFOOperator()
openedMainDS.read(mainDSpath)

# the rest works pretty much the same, but it accepts DS5!
```

My script now seems to be working pretty well for a full DS5 with (separate) roman & italic variable fonts. I still intend to clean it up a bit further, but it’s much nicer than before.

Thanks again for the help here (and also, of course, for this very very helpful library)!
