### ISSUE TITLE
UFOOperator - loadFonts() not working within Robofont

### ISSUE THREAD

**Issue by mathieureguer** [LettError/ufoProcessor#43]
I am having trouble making `UFOOperator.updateFonts([f.asDefcon() for f in AllFonts())` works within RoboFont. 
The passed open font objects are not registered and the operator keeps the source loaded from disk.

I am maybe (probably) doing something wrong, but I am wondering if maybe the testing to find matching font objects is too strict.
UFOOperator is processing `defcon.Font` while Robofont's `RFont.asDefcon()` returns a `DoodleFont` object subclassing `defcon.Font`, rendering the following condition always false:

https://github.com/LettError/ufoProcessor/blob/30ca1e6d4b0cb3295d0bc254cc98931512defb34/Lib/ufoProcessor/ufoOperator.py#L370C25-L370C25

`if haveFont.path == newFont.path and haveFont is newFont:`
(`haveFont` is a `defcon.Font` while `newFont` is a `DoodleFont`)

Changing this line to: `if haveFont.path == newFont.path and isinstance(newFont, self.fontClass):` seems to work around this but maybe I am missing the point of the whole if condition 😬

**Comment by typemytype** [comment]
it checks here if the object is the same... 

`font1 is font2` is the same `id(font1) == id(font2)`, which is maybe wrong as it sis already the same font object. I guess just checking the path is good enough... 

and an additional check could be:`if isinstance(newFont, defcon.Font):` to make sure only defcon objects enters the ufoOperator world

and the last bug here is that line 370 should be `elif`

**Comment by LettError** [comment]
It's too warm to think properly, but if there is a font was referenced to a UFO on disk first, and then it opened in RF, the new one will have the same path, right?
The motivation for this was to be aware of fonts open in RF because the data will change more often.

**Comment by typemytype** [comment]
its this condition: ` haveFont is newFont:` where the id of the font will never be the same when opening the designspace and ufo separately... 

the method `.asDefcon()` is not available outside RF, beter to test on `if hasattr(fontObj, "naked")`

fixing this..

**Comment by mathieureguer** [comment]
Many thanks!

**Comment by mathieureguer** [comment]
Many thanks, closing this :)
