### ISSUE TITLE
UFOOperator - add support for decomposeComponents in makeInstance()?

### ISSUE THREAD

**Issue by mathieureguer** [LettError/ufoProcessor#44]
`makeInstance()` supports generating a limited set of glyphs with the `glyphNames` argument, making it great for generating small previews of more than one glyphs. 
Should it have a `decomposeComponents=False `argument, just like `makeOneGlyph()`, so it can handle composite glyphs gracefully?

I am happy to make a PR if you think that makes sense.

**Comment by typemytype** [comment]
yep, a decomposeComponents argument would be great!

**Comment by LettError** [comment]
Somewhere it needs to do the bookkeeping of finding out which baseglyphs are needed. It's not enough to do a decompose. It needs to render those outlines first!

**Comment by LettError** [comment]
PR very welcome, absolutely :)

**Comment by mathieureguer** [comment]
Shouldn't passing the decomposeComponents argument around to getGlyphMutator() do all the required work already?

**Comment by LettError** [comment]
That could work, and the results would be cached. Still, if you can have a look at the outcomes?

**Comment by mathieureguer** [comment]
It seems to work fine! Well, at least it is generating partial instances, where all requested glyph names are mutated and decomposed: /aacute is decomposed and mutated properly even when /a and /acutecmb are not requested. I am not sure about performance and how to test that though. 😅

Do you want me to add a little test code sample in the `if __name__ == "__main__"`:? (that would mean adding composite glyphs in the DS5 test sources though).

**Comment by mathieureguer** [comment]
Turns out there was already a composite glyphs in the DS5 sample sources 😊
Added a little sample in __main__, let me know if you think I should add anything else.
