### ISSUE TITLE
Output instance doesn’t seem to be following axis map of designspace

### ISSUE THREAD

**Issue by arrowtype** [LettError/ufoProcessor#51]
I’m attempting to use `UFOOperator()` and `makeInstance()` to output UFO instances at a particular Optical Size, from a designspace. Ultimately, I am looking to shift the min opsz up by a bit, from 8 to 12. However, when I generate new UFOs from my designspace, which has a map for the opsz axis, the output instance is a little bit wider than the original variable font at the desired opsz value:

<img width="1687" alt="image" src="https://github.com/LettError/ufoProcessor/assets/45946693/939faab1-f933-4fd7-8fb9-a74da62f3243">

Am I missing some important step in making sure the output instances are following axis mapping? Is `makeInstance()` the wrong function to use in a case like this?

Thank you so much for any insights on this!

<details><summary>Here’s my current code</summary>
<p>

```py
"""
A script to interpolate a UFO at a given location within a provided designspace.
"""

from fontTools.designspaceLib import (InstanceDescriptor)
from fontParts.fontshell import RFont as Font
from ufoProcessor.ufoOperator import UFOOperator
import sys
import os

# get DS path as arg
DSpath = sys.argv[1]

# open main DS & fonts with ufoProcessor.ufoOperator
openedDS = UFOOperator(useVarlib=True)
openedDS.read(DSpath)
openedDS.loadFonts()


for source in openedDS.sources:
    # if "Text" in source.styleName and "sparse" not in source.path:
    if "Text" in source.styleName:

        # same location, but with a shifted Optical Size
        newLoc = {'Optical Size': 12.0, 'Weight': source.location["Weight"], 'Italic': source.location["Italic"]}

        # from https://fonttools.readthedocs.io/en/latest/designspaceLib/python.html#instancedescriptor 
        newInstance = InstanceDescriptor()
        newInstance.path = source.path.replace(".ufo", "-opsz12.ufo")
        newInstance.familyName = source.familyName
        newInstance.styleName = source.styleName
        # newInstance.name = source.familyName.replace(" ","") + source.styleName.replace(" ","")
        newInstance.location = newLoc

        if "sparse" not in source.path:
            # https://github.com/LettError/ufoProcessor/blob/c6a47f04639858993fd752923c8803416c90c9f3/Lib/ufoProcessor/ufoOperator.py#L1133
            generatedInstance = Font(openedDS.makeInstance(newInstance))

        # if "sparse" in source.path, limit glyphset of generated UFO
        if "sparse" in source.path:

            glyphNames = Font(source.path).keys()

            generatedInstance = Font(openedDS.makeInstance(newInstance, glyphNames=glyphNames, bend=True))


        # TODO? rename top layer from "public.default" to "foreground"

        generatedInstance.save(newInstance.path)

        # do some cleanup to sparse support sources
        if "sparse" in generatedInstance.path:
            # remove empty glyphs from sparse supports
            for glyph in generatedInstance:
                if glyph.isEmpty():
                    generatedInstance.removeGlyph(glyph.name)

            # set values so fontmake treats it as a support source
            generatedInstance.lib["com.github.googlei18n.ufo2ft.featureWriters"] = []
            generatedInstance.save()

            os.remove(os.path.join(generatedInstance.path, "features.fea"))
            os.remove(os.path.join(generatedInstance.path, "kerning.plist"))
            os.remove(os.path.join(generatedInstance.path, "groups.plist"))

        print('Saved generated instance to ', newInstance.path)

```

</p>
</details>

**Comment by LettError** [comment]
`makeInstance()` calls `instanceDescriptor.getFullDesignLocation(self.doc)` to make sure all the mapping has been applied. 
https://github.com/LettError/ufoProcessor/blob/c6a47f04639858993fd752923c8803416c90c9f3/Lib/ufoProcessor/ufoOperator.py#L1142C71-L1142C79

I don't really know what you're after, but have you tried this:
`generatedInstance = Font(openedDS.makeInstance(newInstance, glyphNames=glyphNames, bend=False))`

**Comment by arrowtype** [comment]
Thank you so much for the quick reply!

> I don't really know what you're after, but have you tried this:
generatedInstance = Font(openedDS.makeInstance(newInstance, glyphNames=glyphNames, bend=False))

This is the crux of what I have tried, yes. Thank you for verifying that I am not going down the totally incorrect direction.

My goal/expectation is that if I have a designspace with a map, and I output a UFO instance at "opsz=12," it would match the variable font at that same opsz. However, the generated UFO instance is essentially at a smaller opsz than I intend/expect. 

Maybe I am confusing something around how mapping inputs/outputs work. I’ll keep thinking on it.

**Comment by LettError** [comment]
Are your instance locations in userspace or designspace values?

**Comment by LettError** [comment]
> On 4 Oct 2023, at 23:26, Stephen Nixon ***@***.***> wrote:
> 
> My goal/expectation is that if I have a designspace with a map, and I output a UFO instance at "opsz=12," it would match the variable font at that same opsz. However, the generated UFO instance is essentially at a smaller opsz than I intend/expect.
> 
> Maybe I am confusing something around how mapping inputs/outputs work. I’ll keep thinking on it
> 

I can look at something in the afternoon tomorrow. I can't do another shift now..
E

**Comment by arrowtype** [comment]
Okay, no worries at all! I know it’s super late for you, and I didn’t expect you to see this until tomorrow. Thank you so much for your help so far! I’ll update this if I figure it out on my end with your help so far.

**Comment by arrowtype** [comment]
> Are your instance locations in userspace or designspace values?

Ah, that could be it! I suspect that I’m specifying designspace values, when I want userspace values. I’ll look into how I might specify the userspace values for the output.

**Comment by arrowtype** [comment]
Okay, yes, that was indeed the issue. Using RF Skateboard, I could determine that the userspace value of `12` maps to the designspace value of `18.666`, and when I used the latter value in my script, the outputs have exactly glyph widths I expect. 

<img width="1799" alt="image" src="https://github.com/LettError/ufoProcessor/assets/45946693/44416ab4-67b4-40a2-b771-99acae728388">

If there is a good way to convert between user and designspace values in a Python script, I would love to learn about it. I’ll poke around and see if I can find more. But, my immediate question is resolved! Thanks again for pointing me in the right direction.

**Comment by arrowtype** [comment]
Oh, nice, thanks for pointing that out! I was seeing those methods yesterday in the designspaceLib docs, but just wasn't sure how to use them. That is a very helpful example.

**Comment by arrowtype** [comment]
Oh wow! Okay, awesome, I’ve realized what I was missing – thanks for the help along the way, Erik and Frederik!

Yesterday, I was indeed missing a relatively simple thing: I was defining the instance with `instance.location = {'Optical Size': 12}`, and that basic `location` is in terms of the designspace location. 

I have now realized that I can just define an instance like `instance.userLocation = {'Optical Size': 12}`, and UFOOperator outputs it perfectly.

So, here is the old variable font (top), set to opsz 12, and the newly generated source at that location:

<img width="1168" alt="image" src="https://github.com/LettError/ufoProcessor/assets/45946693/1a771c32-f79b-4a8f-97e2-4ef84769c232">

My script is now like this:

<details><summary>My script, now</summary>
<p>

```py
"""
    A script to interpolate a UFO at a given location within a provided designspace, for example,
    to rearrange the boundaries of that designspace, or output a new source.

    Usage:

    python3 <put_folder_path_here>/interpolate-source-at-DS-location.py <put_designspace_path_here>

    The location is hard coded in "newLoc" below, and can be adjusted. This could be made smarter,
    and could be controlled with args fed into the script.
"""

from fontTools.designspaceLib import (InstanceDescriptor)
from fontParts.fontshell import RFont as Font
from ufoProcessor.ufoOperator import UFOOperator
import sys
import os

# get DS path as arg
DSpath = sys.argv[1]


# --------------------------------------
# Some variables for configuration

# Used in the "newLoc" variable below
newOpsz = 12

# a suffix to add to generated UFOs, to avoid overriding existing UFOs
suffix = "opsz12"

# --------------------------------------


# open main DS & fonts with ufoProcessor.ufoOperator
openedDS = UFOOperator(useVarlib=True)
openedDS.read(DSpath)
openedDS.loadFonts()

for source in openedDS.sources:
    # if "Text" in source.styleName and "sparse" not in source.path:
    if "Text" in source.styleName:

        # A shifted Optical Size, but the same location for other axes
        newLoc = {'Optical Size': newOpsz, 'Weight': source.location["Weight"], 'Italic': source.location["Italic"]}

        # from https://fonttools.readthedocs.io/en/latest/designspaceLib/python.html#instancedescriptor 
        newInstance = InstanceDescriptor()
        newInstance.path = source.path.replace(".ufo", f"-{suffix}.ufo")
        newInstance.familyName = source.familyName
        newInstance.styleName = source.styleName
        
        # use userLocation to make opsz 12 work as expected (basic .location will be in the non-mapped "designLocation", see https://github.com/LettError/ufoProcessor/issues/51)
        newInstance.userLocation = newLoc

        if "sparse" not in source.path:
            # https://github.com/LettError/ufoProcessor/blob/c6a47f04639858993fd752923c8803416c90c9f3/Lib/ufoProcessor/ufoOperator.py#L1133
            generatedInstance = Font(openedDS.makeInstance(newInstance))

        # if "sparse" in source.path, limit glyphset of generated UFO
        if "sparse" in source.path:

            glyphNames = Font(source.path).keys()

            generatedInstance = Font(openedDS.makeInstance(newInstance, glyphNames=glyphNames, bend=False))

        # rename top layer from "public.default" to "foreground"
        generatedInstance.defaultLayer.name = "foreground"

        # save it
        generatedInstance.save(newInstance.path)

        # do some cleanup to sparse/support sources
        if "sparse" in generatedInstance.path:
            # remove empty glyphs from sparse supports
            for glyph in generatedInstance:
                if glyph.isEmpty():
                    generatedInstance.removeGlyph(glyph.name)

            # set values so fontmake treats it as a support source
            generatedInstance.lib["com.github.googlei18n.ufo2ft.featureWriters"] = []
            generatedInstance.save()

            os.remove(os.path.join(generatedInstance.path, "features.fea"))
            os.remove(os.path.join(generatedInstance.path, "kerning.plist"))
            os.remove(os.path.join(generatedInstance.path, "groups.plist"))

        print('Saved generated instance to ', newInstance.path)

```

</p>
</details>
