### ISSUE TITLE
ModuleNotFoundError: No module named 'ufoProcessor.ufoOperator'

### ISSUE THREAD

**Issue by arrowtype** [LettError/ufoProcessor#53]
Apologies if this is a stupid question... it feels stupid, but I think I’ve taken the sensible steps to debugging it on my own, and I’m a bit stuck.

I’m trying to use DesignspaceProblems to make a report on a designspace. I can open that DS up in RF DS Editor, and see the problems, but I want to do that in Python, to get a text file.

I’ve set up a venv and installed DesignspaceProblems and ufoProcessor, but when I try to run this simple Python script:

```py
from designspaceProblems import DesignSpaceChecker
print(DesignSpaceChecker)
```

...I get this error:

```console
▶ python3 scripts/check-ds.py
Traceback (most recent call last):
  File "<projectpath>/check-ds.py", line 2, in <module>
    from designspaceProblems import DesignSpaceChecker
  File "<projectpath>/venv/lib/python3.11/site-packages/designspaceProblems/__init__.py", line 10, in <module>
    from ufoProcessor.ufoOperator import UFOOperator
ModuleNotFoundError: No module named 'ufoProcessor.ufoOperator'
```

A similar error results if I try to run this:

```py
from ufoProcessor.ufoOperator import UFOOperator
print(UFOOperator)
```

```console
▶ python3 scripts/check-ds.py
Traceback (most recent call last):
  File "<projectpath>/check-ds.py", line 3, in <module>
    from ufoProcessor.ufoOperator import UFOOperator
ModuleNotFoundError: No module named 'ufoProcessor.ufoOperator'
```

I’ve successfully imported ufoOperator in the recent past, and I don’t think I ran into this issue then.

Just to try to verify that there isn’t a super obvious problem in my Python or venv setup, I’ve also pip installed fontmake and tried this:

```py
from fontmake.font_project import FontProject
print(FontProject)
```

...which seems to work well:

```console
▶ python scripts/check-ds.py
<class 'fontmake.font_project.FontProject'>
```

What might I be missing? Thanks so much for such helpful libraries, and for any insight you might be able to share here!

**Comment by typemytype** [comment]
How did you install those packages? With pip? Or directly from the repo? You will need the latest of ufoProcessor

**Comment by arrowtype** [comment]
I installed with pip:

`pip install -U -r requirements.txt`

From this `requirements.txt`:

```
git+https://github.com/LettError/DesignspaceProblems
ufoProcessor>=1.9
```

**Comment by arrowtype** [comment]
Ah, I can get past this error with:

`pip install -U git+https://github.com/LettError/ufoProcessor`

**Comment by arrowtype** [comment]
Thanks for helping me figure that out!
