### ISSUE TITLE
DecomposePointPen needs identifier kwarg.

### ISSUE THREAD

**Issue by typesupply** [LettError/ufoProcessor#54]
I've been getting a deprecation warning in RF:

```
/Applications/RoboFont.app/Contents/Resources/lib/python3.9/defcon/objects/component.py:186: DeprecationWarning: The addComponent method needs an identifier kwarg. The component's identifier value has been discarded.
```

[Here's where that is coming from.](https://github.com/robotools/defcon/blob/master/Lib/defcon/objects/component.py#L182) Long story short, defcon is gracefully failing when a point pen hasn't been updated to the UFO 3 addComponent method signature. I've been trying to find which point pen is doing this and I think it may be [this line in ufoProcessor.emptyPen.DecomposePointPen](https://github.com/LettError/ufoProcessor/blob/master/Lib/ufoProcessor/emptyPen.py#L21).

**Comment by typemytype** [comment]
fixed... thanks

**Comment by LettError** [comment]
thanks! (I didn't know about this)
