### ISSUE TITLE
`AttributeError` raised when running from terminal

### ISSUE THREAD

**Issue by roberto-arista** [LettError/ufoProcessor#57]
Hey!

I use ufoProcessor to build synthethic sources for our variable fonts production. Working great so far, recently I started to get this traceback at the end of a process:
```
Exception ignored in: <function UFOOperator.__del__ at 0x1112b5080>
Traceback (most recent call last):
  File "/Users/robertoarista/Documents/Repositories/someFolder/.venv/lib/python3.11/site-packages/ufoProcessor/ufoOperator.py", line 485, in __del__
  File "/Users/robertoarista/Documents/Repositories/someFolder/.venv/lib/python3.11/site-packages/ufoProcessor/ufoOperator.py", line 490, in changed
AttributeError: 'NoneType' object has no attribute 'keys'
```

The fonts are generated correctly, and the process runs smoothly, even though I would not expect it with this error message.

**Comment by roberto-arista** [comment]
Happens in:

https://github.com/LettError/ufoProcessor/blob/2ba21b9bfdd429b0fdcacc043102d004f90d71b4/Lib/ufoProcessor/ufoOperator.py#L487-L495

**Comment by LettError** [comment]
That implies `_memoizeCache` is None, rather than the `dict()` it initialises to. Maybe a weird namespace thing? Could you, in the script that calls ufoOperator, print _memoizeCache to see what it thinks it is? Or do you set it to None somewhere?

**Comment by LettError** [comment]
This may not be the right way to test it but a quick look at a terminal python import of ufoOperator shows it is intialised as a dict
```Python 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
>>> import ufoProcessor
>>> import ufoProcessor.ufoOperator
>>> print(ufoProcessor.__file__)
/Users/erik/code/ufoProcessor/Lib/ufoProcessor/__init__.py
>>> print(ufoProcessor.ufoOperator)
<module 'ufoProcessor.ufoOperator' from '/Users/erik/code/ufoProcessor/Lib/ufoProcessor/ufoOperator.py'>
>>> print(ufoProcessor.ufoOperator._memoizeCache)
{}
```

**Comment by roberto-arista** [comment]
I am having a hard time to reproduce it in a smaller environment to share, but I am quite sure that the issue is related to garbage collection. The `__del__` method calls `.changed`, maybe this happens after `_memoizeCache` is deleted. If I comment `__del__` in my code the exception is not raised. Why do you need a `__del__` method? We could check the type of `_memoizeCache` before running `.changed`.

**Comment by LettError** [comment]
Ah that sounds plausible. That would also mean the intervention is only necessary at in `changed`. I was not looking forward to checking for the flavour of the cache dict everywhere it is used. Ok, with this in mind I will look at it. Thank you/

**Comment by roberto-arista** [comment]
Great, thanks!
