### ISSUE TITLE
Copy `com.typemytype.robofont.italicSlantOffset` value

### ISSUE THREAD

**Issue by LettError** [LettError/ufoProcessor#59]
If the sources have an entry for `com.typemytype.robofont.italicSlantOffset`, it would be convenient to copy this value to instances. 

Arguments:
* the glyphs will be drawn with this offset.
* RF will use this value and compensate for it when generating binaries. 
* I don't think the value needs to be interpolated.

Code would need to check specifically if the sources for the discrete location of the instance have the value set.

**Comment by typemytype** [comment]
+1

the fallback value is `0` if that lib key is not available

**Comment by LettError** [comment]
This value relates to glyph geometry. Therefore it would be eligible for interpolation.

**Comment by LettError** [comment]
https://github.com/LettError/ufoProcessor/pull/61
