### ISSUE TITLE
Please fix the tagging

### ISSUE THREAD

**Issue by alerque** [LettError/ufoProcessor#62]
> The tag numbers seem to have run off by themselves. I will keep the Release numbering here.

Pretending the "release number" can be different from the Git tag is silly and makes a lot of work downstream to try to sort out how to package this. The last [PyPi release](https://pypi.org/project/ufoProcessor/#files) is 1.9.0, so the next release does need to be at least 1.9.0 or 1.10.x. The tags as 1.10.x is fine if that's the scheme you want, but drop the nonsense in the titles about it being "1.0.10" and so on. I haven't even looked in the source to see how it self identifies, but that needs to match the tag or you will create no end of confusion and mistakes in downstream packaging and projects that version dependencies.

**Comment by LettError** [comment]
I'm not a friend of git. I will look into it.

**Comment by LettError** [comment]
Syncing the tag numbers with the release numbers to restore order to the galaxy.

**Comment by alerque** [comment]
Thanks.

Also feel free to ping me if you ever need help with Git issues on this of other FOSS font stuff.
