### ISSUE TITLE
Setup bot deployment to PyPI

### ISSUE THREAD

**Issue by miguelsousa** [LettError/ufoProcessor#8]
The deployment will be triggered by git tags. But first it's necessary to setup Travis on this repo.

**Comment by LettError** [comment]
Thanks @miguelsousa!

**Comment by miguelsousa** [comment]
@LettError deployment to PyPI is now working. All you need to do **to issue a new ufoProcessor version** is to add a tag to the last commit, and push that tag (and the commit) to GitHub.

There are a few things you'll need to keep in mind when creating tags:
* tags must follow the versioning scheme defined by [PEP 440](https://www.python.org/dev/peps/pep-0440/)
* each new tag must be greater than the most recent tag
* tags for pre-release versions (alpha, beta, release candidate) must have a suffix in the format `{a|b|c|rc}N` (e.g. `1.0.2a1`)
* once a build has been posted to PyPI it cannot be overwritten. Publishing a new build "consumes" its version number, and forces future version numbers to be greater than the last. Also, if a build is deleted it cannot be restored.

The current process does not issue [GitHub releases](https://github.com/LettError/ufoProcessor/releases). If you'd like to automate that you'll need to [generate an API key](https://github.com/LettError/ufoProcessor/commit/eede03e2118f0322074257ef99271aacf8e24499).

Let me know if you have any questions, and feel free to practice pre-release tagging; we can always delete those builds from PyPI (and the corresponding git tags) as long as you don't increment any of the `major.minor.micro` segments.
